export const CAT_LIST_REQUEST = 'CAT_LIST_REQUEST';
export const CAT_LIST_SUCCESS = 'CAT_LIST_SUCCESS';
export const CAT_LIST_FAIL = 'CAT_LIST_FAIL';

export const CAT_PRODUCT_LIST_REQUEST = 'CAT_PRODUCT_LIST_REQUEST';
export const CAT_PRODUCT_LIST_SUCCESS = 'CAT_PRODUCT_LIST_SUCCESS';
export const CAT_PRODUCT_LIST_FAIL = 'CAT_PRODUCT_LIST_FAIL';

export const CREATE_CAT_REQUEST = 'CREATE_CAT_REQUEST';
export const CREATE_CAT_SUCCESS = 'CREATE_CAT_SUCCESS';
export const CREATE_CAT_FAIL = 'CREATE_CAT_FAIL';
